### ISSUE TITLE
Key Window not resigning

### ISSUE THREAD

**Issue by toofah** [agilityvision/FFGlobalAlertController#2]
This solution worked for me until I started compiling my code with Xcode 7 for iOS 9.  Now it seems that the key window for the new alert never resigns.  In my app this makes it so that I am unable to tap through to underlying views after I show an alert.

I was able to learn more by observing the following notifications:
    [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidBecomeVisibleNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
        NSLog(@"UIWindowDidBecomeVisibleNotification");
    }];
    [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidBecomeHiddenNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
        NSLog(@"UIWindowDidBecomeHiddenNotification");
    }];
    [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidBecomeKeyNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
        NSLog(@"UIWindowDidBecomeKeyNotification");
    }];
    [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidResignKeyNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
        NSLog(@"UIWindowDidResignKeyNotification");
    }];

**Comment by toofah** [comment]
If I go back to Xcode 6 and iOS 8 simulator I get UIWindowDidBecomeKeyNotification when the alert closes.  This notification does not fire in iOS 9 case.

**Comment by agilityvision** [comment]
I did not have the experience you are having. It works fine on iOS 9 for me. But I did go ahead and add in viewDidDisappear method and in it I hide and nil out the UIWindow. Should take care of it. Let me know and I will close this out.

**Comment by toofah** [comment]
Thanks, that worked great for me!

If you paste those observers into the viewDidLoad method of the example like this you will see that the notifications are missing without your recent change.
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidBecomeVisibleNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
      NSLog(@"UIWindowDidBecomeVisibleNotification");
  }];
  [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidBecomeHiddenNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
      NSLog(@"UIWindowDidBecomeHiddenNotification");
  }];
  [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidBecomeKeyNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
      NSLog(@"UIWindowDidBecomeKeyNotification");
  }];
  [[NSNotificationCenter defaultCenter] addObserverForName:@"UIWindowDidResignKeyNotification" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *notification) {
      NSLog(@"UIWindowDidResignKeyNotification");
  }];
  }
